import { createContext, useContext, useState } from "react";

const CommonContext = createContext();

export const CommonContextProvider = ({ children }) => {
	const [categories, setCategories] = useState([
		"LLM",
		"AI Tools",
		"Backend",
		"Hosting",
		"Frontend",
		"Database",
		"Cloud",
		"Code Tools",
		"Dev Platforms",
		"Learning",
		"Productivity",
		"Other",
	]);

	const categoryColors = {
		"AI Tools": "from-purple-500 to-pink-500",
		"AI Agent": "from-pink-500 to-rose-500",
		LLM: "from-violet-500 to-purple-500",
		Backend: "from-green-500 to-emerald-500",
		Hosting: "from-blue-500 to-cyan-500",
		Frontend: "from-yellow-500 to-orange-500",
		Database: "from-red-500 to-orange-500",
		Cloud: "from-sky-500 to-indigo-500",
		"Code Tools": "from-orange-500 to-red-500",
		"Dev Platforms": "from-blue-500 to-purple-500",
		Learning: "from-teal-500 to-cyan-500",
		Productivity: "from-emerald-500 to-teal-500",
		Other: "from-gray-500 to-gray-600",
	};

	const getCatColor = (cat) => categoryColors[cat] || categoryColors.Other;

	const styles = {
		page: {
			minHeight: "100vh",
			background: "#0d0f14",
			display: "flex",
			flexDirection: "column",
			alignItems: "center",
			justifyContent: "center",
			// padding: "24px 16px",
			position: "relative",
			overflow: "hidden",
		},
		grid: {
			position: "fixed",
			inset: 0,
			backgroundImage: `
			linear-gradient(rgba(108,99,255,0.04) 1px, transparent 1px),
			linear-gradient(90deg, rgba(108,99,255,0.04) 1px, transparent 1px)
		`,
			backgroundSize: "40px 40px",
			pointerEvents: "none",
			zIndex: 0,
		},
		glow: {
			position: "fixed",
			top: "-200px",
			left: "50%",
			transform: "translateX(-50%)",
			width: "600px",
			height: "600px",
			background:
				"radial-gradient(circle, rgba(108,99,255,0.12) 0%, transparent 70%)",
			pointerEvents: "none",
			zIndex: 0,
		},
		navLeft: {
			display: "flex",
			alignItems: "center",
			gap: "8px",
			minWidth: "120px",
		},
		navLinks: {
			display: "flex",
			alignItems: "center",
			gap: "12px",
		},
		accent: { color: "#6c63ff" },
		searchWrap: {
			flex: 1,
			maxWidth: "480px",
			display: "flex",
			alignItems: "center",
			gap: "8px",
			background: "#1e2330",
			border: "1px solid #2a3044",
			borderRadius: "8px",
			padding: "0 12px",
			height: "34px",
		},
		searchIcon: { color: "#3a4260", fontSize: "16px" },
		searchInput: {
			flex: 1,
			background: "none",
			border: "none",
			outline: "none",
			color: "#e8eaf0",
			fontSize: "13px",
		},
		clearSearch: {
			background: "none",
			border: "none",
			color: "#3a4260",
			cursor: "pointer",
			fontSize: "12px",
			padding: "2px",
		},
		navRight: {
			display: "flex",
			alignItems: "center",
			gap: "10px",
			marginLeft: "auto",
		},
		btnGhost: {
			padding: "8px 18px",
			borderRadius: "8px",
			border: "1px solid #2a3044",
			background: "transparent",
			color: "#8b9ab8",
			fontSize: "13px",
			fontWeight: "500",
			textDecoration: "none",
			transition: "all 0.15s",
		},
		btnPrimary: {
			padding: "8px 18px",
			borderRadius: "8px",
			background: "linear-gradient(135deg, #6c63ff, #4f46e5)",
			color: "#fff",
			fontSize: "13px",
			fontWeight: "600",
			textDecoration: "none",
			border: "none",
		},
		badge: {
			display: "inline-flex",
			alignItems: "center",
			gap: "8px",
			background: "rgba(108,99,255,0.1)",
			border: "1px solid rgba(108,99,255,0.25)",
			borderRadius: "20px",
			padding: "5px 14px",
			fontSize: "12px",
			color: "#a5a0ff",
			fontWeight: "500",
			marginBottom: "28px",
		},
		badgeDot: {
			width: "6px",
			height: "6px",
			borderRadius: "50%",
			background: "#6c63ff",
			display: "inline-block",
		},
		heroHeading: {
			fontSize: "clamp(36px, 6vw, 64px)",
			fontWeight: "800",
			lineHeight: "1.1",
			color: "#e8eaf0",
			margin: "0 0 20px",
			letterSpacing: "-0.02em",
		},
		heroAccent: {
			background: "linear-gradient(135deg, #6c63ff, #3b82f6)",
			WebkitBackgroundClip: "text",
			WebkitTextFillColor: "transparent",
			backgroundClip: "text",
		},
		heroSub: {
			fontSize: "16px",
			color: "#8b9ab8",
			lineHeight: "1.6",
			maxWidth: "520px",
			margin: "0 0 36px",
		},
		heroCta: {
			display: "flex",
			gap: "12px",
			marginBottom: "52px",
			flexWrap: "wrap",
			justifyContent: "center",
		},
		btnPrimaryLg: {
			padding: "12px 28px",
			borderRadius: "10px",
			background: "linear-gradient(135deg, #6c63ff, #4f46e5)",
			color: "#fff",
			fontSize: "14px",
			fontWeight: "600",
			textDecoration: "none",
			border: "none",
			display: "inline-block",
		},
		btnGhostLg: {
			padding: "12px 28px",
			borderRadius: "10px",
			border: "1px solid #2a3044",
			background: "transparent",
			color: "#8b9ab8",
			fontSize: "14px",
			fontWeight: "500",
			textDecoration: "none",
			display: "inline-block",
		},
		addBtn: {
			padding: "6px 14px",
			background: "linear-gradient(135deg,#6c63ff,#4f46e5)",
			border: "none",
			borderRadius: "6px",
			color: "#fff",
			fontSize: "12px",
			fontWeight: "600",
			cursor: "pointer",
			whiteSpace: "nowrap",
		},
		avatar: {
			width: "30px",
			height: "30px",
			borderRadius: "50%",
			background: "linear-gradient(135deg,#6c63ff,#3b82f6)",
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			fontSize: "11px",
			fontWeight: "700",
			cursor: "pointer",
			flexShrink: 0,
		},
		logoutBtn: {
			background: "none",
			border: "1px solid #2a3044",
			borderRadius: "6px",
			color: "#5a6a8a",
			cursor: "pointer",
			padding: "4px 8px",
			fontSize: "14px",
		},
		body: {
			display: "grid",
			gridTemplateColumns: "196px 1fr 220px",
			flex: 1,
			overflow: "hidden",
		},
		terminal: {
			width: "100%",
			maxWidth: "520px",
			background: "#0a0c10",
			border: "1px solid #2a3044",
			borderRadius: "12px",
			overflow: "hidden",
			textAlign: "left",
		},
		terminalBar: {
			display: "flex",
			alignItems: "center",
			gap: "6px",
			padding: "10px 16px",
			borderBottom: "1px solid #1e2330",
			background: "#111318",
		},
		dot: {
			width: "10px",
			height: "10px",
			borderRadius: "50%",
			display: "inline-block",
		},
		terminalTitle: {
			fontSize: "11px",
			color: "#3a4260",
			marginLeft: "8px",
			fontFamily: "monospace",
		},
		terminalBody: {
			padding: "16px 20px",
			fontFamily: "monospace",
			fontSize: "13px",
			lineHeight: "1.8",
		},
		terminalLine: {
			display: "flex",
			alignItems: "center",
		},
		prompt: { color: "#6c63ff" },
		cmd: { color: "#e8eaf0" },
		arrow: { color: "#22c55e" },
		item: { color: "#a5a0ff" },
		dimText: { color: "#3a4260" },
		tagText: { color: "#6c63ff" },
		section: {
			position: "relative",
			zIndex: 1,
			maxWidth: "900px",
			margin: "0 auto",
			padding: "80px 24px",
			textAlign: "center",
		},
		sectionEyebrow: {
			fontSize: "12px",
			fontWeight: "600",
			color: "#6c63ff",
			textTransform: "uppercase",
			letterSpacing: "0.08em",
			marginBottom: "12px",
		},
		sectionHeading: {
			fontSize: "clamp(24px, 4vw, 36px)",
			fontWeight: "700",
			color: "#e8eaf0",
			margin: "0 0 48px",
			letterSpacing: "-0.01em",
		},
		featureGrid: {
			display: "grid",
			gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
			gap: "16px",
		},
		featureCard: {
			background: "#161920",
			border: "1px solid #2a3044",
			borderRadius: "12px",
			padding: "24px 20px",
			textAlign: "left",
		},
		featureIcon: {
			fontSize: "24px",
			marginBottom: "12px",
		},
		featureTitle: {
			fontSize: "14px",
			fontWeight: "700",
			color: "#e8eaf0",
			margin: "0 0 8px",
		},
		featureDesc: {
			fontSize: "13px",
			color: "#8b9ab8",
			lineHeight: "1.5",
			margin: 0,
		},
		stackSection: {
			position: "relative",
			zIndex: 1,
			textAlign: "center",
			padding: "0 24px 80px",
		},
		stackLabel: {
			fontSize: "11px",
			color: "#3a4260",
			textTransform: "uppercase",
			letterSpacing: "0.1em",
			marginBottom: "16px",
		},
		stackRow: {
			display: "flex",
			flexWrap: "wrap",
			gap: "10px",
			justifyContent: "center",
		},
		stackPill: {
			padding: "6px 16px",
			borderRadius: "20px",
			background: "#161920",
			border: "1px solid #2a3044",
			fontSize: "12px",
			color: "#5a6a8a",
			fontWeight: "500",
		},
		ctaSection: {
			position: "relative",
			zIndex: 1,
			padding: "0 24px 80px",
			maxWidth: "700px",
			margin: "0 auto",
		},
		ctaCard: {
			background: "#161920",
			border: "1px solid #2a3044",
			borderRadius: "16px",
			padding: "52px 40px",
			textAlign: "center",
			position: "relative",
			overflow: "hidden",
		},
		ctaGlow: {
			position: "absolute",
			top: "-60px",
			left: "50%",
			transform: "translateX(-50%)",
			width: "300px",
			height: "200px",
			background:
				"radial-gradient(circle, rgba(108,99,255,0.15) 0%, transparent 70%)",
			pointerEvents: "none",
		},
		ctaHeading: {
			fontSize: "clamp(22px, 4vw, 32px)",
			fontWeight: "700",
			color: "#e8eaf0",
			margin: "0 0 12px",
			position: "relative",
		},
		ctaSub: {
			fontSize: "14px",
			color: "#8b9ab8",
			margin: "0 0 28px",
			position: "relative",
		},
		footer: {
			position: "relative",
			zIndex: 1,
			borderTop: "1px solid #1e2330",
			padding: "28px 40px",
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			flexWrap: "wrap",
			gap: "12px",
		},
		footerText: {
			fontSize: "12px",
			color: "#3a4260",
			margin: 0,
		},
		footerLink: {
			color: "#5a6a8a",
			textDecoration: "none",
		},
		sideSection: { marginBottom: "16px" },
		sideLabel: {
			fontSize: "10px",
			fontWeight: "600",
			color: "#3a4260",
			textTransform: "uppercase",
			letterSpacing: ".08em",
			padding: "0 8px 6px",
		},
		sideItem: {
			display: "flex",
			alignItems: "center",
			gap: "8px",
			padding: "6px 8px",
			borderRadius: "6px",
			cursor: "pointer",
			color: "#5a6a8a",
			fontSize: "12px",
			fontWeight: "500",
			transition: "all .15s",
			marginBottom: "1px",
		},
		sideItemActive: { background: "#1e2330", color: "#e8eaf0" },
		sideBadge: {
			marginLeft: "auto",
			background: "#f59e0b",
			color: "#0d0f14",
			borderRadius: "10px",
			padding: "1px 6px",
			fontSize: "10px",
			fontWeight: "700",
		},
		sideCount: { marginLeft: "auto", color: "#3a4260", fontSize: "11px" },
		catDot: {
			width: "7px",
			height: "7px",
			borderRadius: "2px",
			flexShrink: 0,
		},
		tagCloud: {
			display: "flex",
			flexWrap: "wrap",
			gap: "4px",
			padding: "0 4px",
		},
		tagPill: {
			padding: "3px 8px",
			borderRadius: "10px",
			background: "#1e2330",
			border: "1px solid #2a3044",
			fontSize: "10px",
			color: "#5a6a8a",
			cursor: "pointer",
		},
		main: { overflowY: "auto", padding: "20px" },
		filterRow: {
			display: "flex",
			gap: "6px",
			flexWrap: "wrap",
			marginBottom: "16px",
		},
		filterChip: {
			padding: "4px 12px",
			borderRadius: "16px",
			border: "1px solid #2a3044",
			background: "#161920",
			color: "#5a6a8a",
			fontSize: "11px",
			fontWeight: "500",
			cursor: "pointer",
		},
		filterChipActive: {
			background: "#4f46e5",
			borderColor: "#6c63ff",
			color: "#fff",
		},
		sectionBlock: { marginBottom: "28px" },
		sectionHeader: { marginBottom: "12px" },
		sectionTitle: {
			fontSize: "13px",
			fontWeight: "600",
			color: "#8b9ab8",
			display: "flex",
			alignItems: "center",
			gap: "6px",
		},
		catCount: {
			marginLeft: "6px",
			fontSize: "11px",
			color: "#3a4260",
			fontWeight: "400",
		},
		quickGrid: {
			display: "grid",
			gridTemplateColumns: "repeat(auto-fill,minmax(110px,1fr))",
			gap: "10px",
		},
		quickCard: {
			background: "#161920",
			border: "1px solid #2a3044",
			borderRadius: "10px",
			padding: "14px 10px",
			textAlign: "center",
			cursor: "pointer",
			textDecoration: "none",
			display: "block",
			transition: "all .15s",
		},
		quickCardAdd: {
			background: "#161920",
			border: "1px dashed #2a3044",
			borderRadius: "10px",
			padding: "14px 10px",
			textAlign: "center",
			cursor: "pointer",
			display: "flex",
			flexDirection: "column",
			alignItems: "center",
			gap: "8px",
		},
		quickIcon: {
			width: "38px",
			height: "38px",
			borderRadius: "9px",
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			margin: "0 auto 8px",
		},
		quickAddIcon: { fontSize: "20px", color: "#3a4260" },
		quickName: {
			fontSize: "11px",
			fontWeight: "600",
			color: "#8b9ab8",
			display: "block",
		},
		quickCat: {
			fontSize: "10px",
			color: "#3a4260",
			marginTop: "2px",
			display: "block",
		},
		resourceGrid: {
			display: "grid",
			gridTemplateColumns: "repeat(auto-fill,minmax(210px,1fr))",
			gap: "10px",
		},
		cardTop: {
			display: "flex",
			alignItems: "flex-start",
			justifyContent: "space-between",
			marginBottom: "10px",
		},
		cardIcon: {
			width: "34px",
			height: "34px",
			borderRadius: "8px",
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			flexShrink: 0,
		},
		cardName: {
			fontSize: "13px",
			fontWeight: "600",
			color: "#e8eaf0",
			marginBottom: "2px",
		},
		cardType: { fontSize: "10px", color: "#3a4260", marginBottom: "6px" },
		cardNotes: {
			fontSize: "11px",
			color: "#5a6a8a",
			lineHeight: "1.4",
			marginBottom: "8px",
			display: "-webkit-box",
			WebkitLineClamp: 2,
			WebkitBoxOrient: "vertical",
			overflow: "hidden",
		},
		cardTags: {
			display: "flex",
			gap: "4px",
			flexWrap: "wrap",
			marginBottom: "8px",
		},
		tag: {
			padding: "2px 6px",
			borderRadius: "4px",
			fontSize: "10px",
			fontWeight: "500",
		},
		cardFooter: {
			display: "flex",
			alignItems: "center",
			justifyContent: "space-between",
		},
		visits: { fontSize: "10px", color: "#3a4260" },
		cardActions: { display: "flex", gap: "2px" },
		iconBtn: {
			background: "none",
			border: "none",
			color: "#3a4260",
			cursor: "pointer",
			fontSize: "14px",
			padding: "3px 5px",
			borderRadius: "4px",
			textDecoration: "none",
			lineHeight: 1,
		},
		emptyState: { textAlign: "center", padding: "60px 20px" },
		emptyIcon: { fontSize: "40px", color: "#2a3044", marginBottom: "12px" },
		emptyTitle: {
			fontSize: "16px",
			fontWeight: "600",
			color: "#5a6a8a",
			marginBottom: "6px",
		},
		emptyDesc: { fontSize: "13px", color: "#3a4260", marginBottom: "20px" },
		emptyBtn: {
			padding: "8px 20px",
			background: "linear-gradient(135deg,#6c63ff,#4f46e5)",
			border: "none",
			borderRadius: "8px",
			color: "#fff",
			fontSize: "13px",
			fontWeight: "600",
			cursor: "pointer",
		},
		loadingState: {
			display: "flex",
			flexDirection: "column",
			alignItems: "center",
			justifyContent: "center",
			height: "300px",
			gap: "16px",
		},
		spinner: {
			width: "28px",
			height: "28px",
			border: "2px solid #2a3044",
			borderTopColor: "#6c63ff",
			borderRadius: "50%",
			animation: "spin 0.7s linear infinite",
			display: "inline-block",
		},
		loadingText: { fontSize: "13px", color: "#3a4260" },
		rightPanel: {
			background: "#161920",
			// borderLeft: "1px solid #2a3044",
			padding: "16px 12px",
			// overflowY: "auto",
		},
		panelSection: { marginBottom: "20px" },
		panelTitle: {
			fontSize: "11px",
			fontWeight: "600",
			color: "#5a6a8a",
			textTransform: "uppercase",
			letterSpacing: ".06em",
			marginBottom: "10px",
			display: "flex",
			gap: "8px",
		},
		statGrid: {
			display: "grid",
			gridTemplateColumns: "1fr 1fr",
			gap: "6px",
		},
		statCard: {
			background: "#1e2330",
			border: "1px solid #2a3044",
			borderRadius: "8px",
			padding: "10px",
			textAlign: "center",
		},
		statNum: { fontSize: "20px", fontWeight: "700", color: "#e8eaf0" },
		statLabel: { fontSize: "10px", color: "#3a4260", marginTop: "2px" },
		visitRow: {
			display: "flex",
			alignItems: "center",
			gap: "8px",
			padding: "5px 0",
			borderBottom: "1px solid #1e2330",
		},
		visitDot: {
			width: "24px",
			height: "24px",
			borderRadius: "6px",
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			fontSize: "9px",
			fontWeight: "700",
			flexShrink: 0,
		},
		visitName: {
			flex: 1,
			fontSize: "11px",
			color: "#8b9ab8",
			overflow: "hidden",
			textOverflow: "ellipsis",
			whiteSpace: "nowrap",
		},
		visitCount: { fontSize: "11px", color: "#3a4260", flexShrink: 0 },
		userCard: {
			display: "flex",
			alignItems: "center",
			gap: "10px",
			marginBottom: "10px",
		},
		userAvatar: {
			width: "32px",
			height: "32px",
			borderRadius: "50%",
			background: "linear-gradient(135deg,#6c63ff,#3b82f6)",
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			fontSize: "11px",
			fontWeight: "700",
			flexShrink: 0,
		},
		userName: { fontSize: "12px", fontWeight: "600", color: "#e8eaf0" },
		userEmail: { fontSize: "10px", color: "#3a4260" },
		logoutFullBtn: {
			width: "100%",
			padding: "7px",
			background: "#1e2330",
			border: "1px solid #2a3044",
			borderRadius: "6px",
			color: "#5a6a8a",
			fontSize: "12px",
			cursor: "pointer",
		},
		overlay: {
			position: "fixed",
			inset: 0,
			background: "rgba(0,0,0,.7)",
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			zIndex: 100,
			backdropFilter: "blur(2px)",
		},
		modal: {
			background: "#161920",
			border: "1px solid #2a3044",
			borderRadius: "14px",
			padding: "24px",
			width: "480px",
			maxWidth: "90vw",
			maxHeight: "85vh",
			overflowY: "auto",
		},
		modalHeader: {
			display: "flex",
			alignItems: "center",
			justifyContent: "space-between",
			marginBottom: "20px",
		},
		modalTitle: { fontSize: "16px", fontWeight: "700", color: "#e8eaf0" },
		closeBtn: {
			background: "none",
			border: "1px solid #2a3044",
			borderRadius: "6px",
			color: "#5a6a8a",
			cursor: "pointer",
			padding: "4px 8px",
			fontSize: "14px",
		},
		form: { display: "flex", flexDirection: "column", gap: "14px" },
		field: { display: "flex", flexDirection: "column", gap: "5px" },
		fieldRow: { display: "flex", gap: "12px" },
		label: { fontSize: "11px", fontWeight: "600", color: "#8b9ab8" },
		input: {
			background: "#1e2330",
			border: "1px solid #2a3044",
			borderRadius: "7px",
			padding: "9px 12px",
			color: "#e8eaf0",
			fontSize: "13px",
			outline: "none",
			width: "100%",
			transition: "border-color .15s",
		},
		hint: { fontSize: "10px", color: "#3a4260", margin: "2px 0 0" },
		submitBtn: {
			padding: "11px",
			background: "linear-gradient(135deg,#6c63ff,#4f46e5)",
			border: "none",
			borderRadius: "8px",
			color: "#fff",
			fontSize: "13px",
			fontWeight: "600",
			cursor: "pointer",
			marginTop: "4px",
		},
		card: {
			background: "#161920",
			border: "1px solid #2a3044",
			borderRadius: "16px",
			padding: "40px 36px",
			width: "100%",
			maxWidth: "400px",
			position: "relative",
			transition: "border-color .15s",
			zIndex: 1,
		},
		logoRow: {
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			gap: "10px",
			marginBottom: "28px",
		},
		logoHex: {
			width: "36px",
			height: "36px",
			background: "linear-gradient(135deg, #6c63ff, #3b82f6)",
			borderRadius: "9px",
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			fontWeight: "900",
			fontSize: "13px",
			color: "#fff",
		},
		logoText: {
			fontWeight: "700",
			fontSize: "20px",
			color: "#e8eaf0",
		},
		logoAccent: {
			color: "#6c63ff",
		},
		heading: {
			fontSize: "22px",
			fontWeight: "700",
			color: "#e8eaf0",
			margin: "0 0 6px",
			textAlign: "center",
		},
		subheading: {
			fontSize: "13px",
			color: "#5a6a8a",
			margin: "0 0 24px",
			textAlign: "center",
		},
		errorBox: {
			background: "rgba(239,68,68,.12)",
			border: "1px solid rgba(239,68,68,.25)",
			borderRadius: "8px",
			padding: "10px 14px",
			display: "flex",
			alignItems: "center",
			gap: "10px",
			marginBottom: "20px",
			fontSize: "13px",
			color: "#ef4444",
		},
		errorIcon: {
			background: "#ef4444",
			color: "#fff",
			borderRadius: "50%",
			width: "20px",
			height: "20px",
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			fontSize: "12px",
			fontWeight: "700",
			flexShrink: 0,
		},
		labelRow: {
			display: "flex",
			justifyContent: "space-between",
			alignItems: "center",
			marginBottom: "2px",
		},
		btn: {
			padding: "11px",
			background: "linear-gradient(135deg, #6c63ff, #4f46e5)",
			border: "none",
			borderRadius: "8px",
			color: "#fff",
			fontSize: "14px",
			fontWeight: "600",
			cursor: "pointer",
			width: "100%",
			transition: "opacity 0.2s",
		},
		btnInner: {
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			gap: "10px",
		},
		link: {
			color: "#6c63ff",
			textDecoration: "none",
			fontWeight: "500",
		},
		tagline: {
			position: "relative",
			zIndex: 1,
			fontSize: "12px",
			color: "#3a4260",
			marginTop: "28px",
			textAlign: "center",
		},
		taglineAccent: {
			color: "#6c63ff",
		},
	};

	const systemStatus = [
		{ name: "API", status: "operational" },
		{ name: "Database", status: "operational" },
		{ name: "Search", status: "operational" },
		{ name: "Sync", status: "operational" },
	];

	const addCategory = (newCategory) => {
		if (!categories.includes(newCategory)) {
			setCategories([...categories, newCategory]);
		}
	};

	const CommonContextFeatures = {
		categories,
		categoryColors,
		addCategory,
		styles,
		systemStatus,
		getCatColor,
	};

	return (
		<CommonContext.Provider value={CommonContextFeatures}>
			{children}
		</CommonContext.Provider>
	);
};

export const useCommon = () => {
	const ctx = useContext(CommonContext);
	if (!ctx) {
		throw new Error("useData must be used within a CommonContextProvider");
	}
	return ctx;
};
